services:
  - type: web
    name: mivallecanta
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: gunicorn mivalle_main.wsgi:application
    envVars:      
      - key: SECRET_KEY
          generateValue: true
      - key: DEBUG
          value: "False"      
databases:
  - name: mivallecantaDB
    plan: free